Make `Error::with_source` use `Into<BoxedError>`
This bound is strictly more general due to a blanket impl in libstd, and
allows using `BoxedError` directly, which does not implement `Error`.